version: '3.8'

volumes:
  user_data:
    driver: local

networks:
  server_network:
    driver: bridge
    ipam:
      config:
        - subnet: 192.168.1.0/24
  client_network:
    driver: bridge
    ipam:
      config:
        - subnet: 192.168.2.0/24

services:
  router:
    image: router-image
    container_name: router
    depends_on:
      - ddns
    networks:
      server_network:
        ipv4_address: 192.168.1.100
      client_network:
        ipv4_address: 192.168.2.100
    cap_add:
      - NET_ADMIN
    privileged: true
    sysctls:
      net.ipv4.ip_forward: 1
    stdin_open: true
    tty: true
    dns:
      - 192.168.1.10
  
  server:
    image: server-image
    container_name: server
    depends_on:
      - ddns
    networks:
      server_network:
        ipv4_address: 192.168.1.2
    stdin_open: true
    tty: true
    dns:
      - 192.168.1.10
    privileged: true
    cap_add:
      - NET_ADMIN

  client1:
    image: client-image
    container_name: client1
    depends_on:
      - ddns
    volumes:
      - user_data:/app/user_data
    networks:
      client_network:
        ipv4_address: 192.168.2.2
    stdin_open: true
    tty: true
    dns:
      - 192.168.1.10
    extra_hosts:
      - "gateway:192.168.2.100"
    privileged: true
    cap_add:
      - NET_ADMIN

  client2:
    image: client-image
    container_name: client2
    depends_on:
      - ddns
    volumes:
      - user_data:/app/user_data
    networks:
      client_network:
        ipv4_address: 192.168.2.3
    stdin_open: true
    tty: true
    dns:
      - 192.168.1.10
    extra_hosts:
      - "gateway:192.168.2.100"
    privileged: true
    cap_add:
      - NET_ADMIN

  client3:
    image: client-image
    container_name: client3
    depends_on:
      - ddns
    volumes:
      - user_data:/app/user_data
    networks:
      client_network:
        ipv4_address: 192.168.2.4
    stdin_open: true
    tty: true
    dns:
      - 192.168.1.10
    extra_hosts:
      - "gateway:192.168.2.100"
    privileged: true
    cap_add:
      - NET_ADMIN
  ddns:
    image: coredns/coredns
    container_name: ddns
    volumes:
      - ./Corefile:/Corefile
      - ./db.server:/db.server
    ports:
      - "8053:53/udp"
    networks:
      server_network:
        ipv4_address: 192.168.1.10
    stdin_open: true
    tty: true
    privileged: true
    cap_add:
      - NET_ADMIN
